### ISSUE TITLE
Tech stack and building procedure

### ISSUE THREAD

**Issue by passionate2023** [thesephist/monocle#3]
Hi,

I'm eager to know the following and can you pls help me

what are the technologies involved?
steps or commands to build or bundle this app to deploy in servers - windows or linux or mac?
windows throws lots of errors as many commands couldn't recognize

can you share some insights on how to buid/deploy this

thank you

**Comment by thesephist** [comment]
Quoting the [README](https://github.com/thesephist/monocle) at the front page of the repo here:

>_**⚠️ Note**: If you're reading this section to try to set up and run your own Monocle instance, I applaud your audacity, but it might not be super easy or fruitful -- Monocle's modules are pretty specific not only to my data sources, but also the way I structure those files. I won't stop you from trying to build your own search index, but be warned: it might not work, and I'm probably not going to do tech support. For this reason, this section is also written in first-person, mostly for my future reference._

As mentioned above this repo and the code is very specific to my (1) tech stack (2) personal data situation and (3) infrastructure that I run this app within (including lots of other apps that cooperate to make Monocle work). Unfortunately I don't have the capacity to help other folks set it up on their own. For that reason, I'm going to close this issue.

If you want a similar tool in your life, I can recommend the excellent [Operand](https://operand.ai/) that my friend Morgan runs.

**Comment by passionate2023** [comment]
Operand is closed. Can you just please help with just steps alone?
