### ISSUE TITLE
Where are the missing files?

### ISSUE THREAD

**Issue by Pravinms24** [thesephist/monocle#4]
Hi,

Below are the commands i tried in linux, however go stuck with the next step

sudo apt update
sudo apt install ink
sudo apt install golang (or) go.dev/install and download go directory
set path usr/local/go/bin

root@pop-os:/etc/systemd/system# sudo systemctl daemon-reload
root@pop-os:/etc/systemd/system# systemctl start monocle.service
Job for monocle.service failed because the control process exited with error code.
See "systemctl status monocle.service" and "journalctl -xe" for details.
root@pop-os:/etc/systemd/system# systemctl status monocle.service
● monocle.service - monocle server
     Loaded: loaded (/etc/systemd/system/monocle.service; disabled; vendor pres>
     Active: failed (Result: exit-code) since Sat 2022-11-19 16:45:29 IST; 11s >
    Process: 16672 ExecStartPre=/bin/mkdir -p /var/log/monocle (code=exited, st>

Nov 19 16:45:29 pop-os systemd[1]: monocle.service: Scheduled restart job, rest>
Nov 19 16:45:29 pop-os systemd[1]: Stopped monocle server.
Nov 19 16:45:29 pop-os systemd[1]: monocle.service: Start request repeated too >
Nov 19 16:45:29 pop-os systemd[1]: monocle.service: Failed with result 'exit-co>
Nov 19 16:45:29 pop-os systemd[1]: Failed to start monocle server.
lines 1-10/10 (END)

----
Pls help with the missing files which needed for execution or building

Thanks

**Comment by thesephist** [comment]
Please see my response to #3.
