### ISSUE TITLE
searching "tools for thought" on monocle.surge.sh only shows "loading index..."

### ISSUE THREAD

**Issue by happy15** [thesephist/monocle#5]
hi, I tried to search "tools for thought" on monocle.surge.sh, it only showed "loading index...". 

Did I miss anything?

**Comment by thesephist** [comment]
Looks to be working just fine for me:

![Screen Shot 2023-01-02 at 05 39 11](https://user-images.githubusercontent.com/5403917/210220561-66982951-9231-467f-bd0f-9229508938d1.png)

The search index is loaded onto the client, so if you're on a very slow internet connection, you might need to wait a bit (if you want to dig really deep, check the Network pane in your devtools that the index files are being downloaded properly).
